# Метод простой итерации

In [1]:
import numpy as np

In [45]:
def method_iteration(A, B, max_iterations=100, tolerance=1e-10):
    n_rows, n_cols = A.shape

    x = np.zeros((n_rows, 1))
    for i in range(n_rows):
        x[i] = B[i]/A[i][i]
        
    for k in range(max_iterations):
        x_new = np.zeros((n_rows, 1))

        for i in range(n_rows):
            s = 0
            
            for j in range(n_cols):
                if j != i:
                    s += A[i][j] * x[j]
            x_new[i] = (B[i] - s) / A[i][i] 
        #print(x)
        if np.linalg.norm(x_new - x) < tolerance:
            #print(x_new)
            print(f'Количество итераций: {k}')
            return x_new

        x = x_new
    print(f'Количество итераций: {k}')
    return x_new

In [15]:
A = np.array([[20.9, 1.2, 2.1, .9],[1.2, 21.2, 1.5, 2.5],[2.1, 1.5, 19.8, 1.3], [.9, 2.5, 1.3, 32.1]])
B = np.array([[21.7],[27.46],[28.76], [49.72]])

In [16]:
method_iteration(A, B, tolerance=1e-3)

array([[0.80001962],
       [1.00002128],
       [1.20002228],
       [1.40001483]])

# Метод Зейделя

In [49]:
def method_seidel(A, b, x0, tol=1e-10, max_iter=1000):
    n = len(b)
    x = x0.copy()

    for k in range(max_iter):
        for i in range(n):
            x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i)) - sum(A[i][j] * x0[j] for j in range(i + 1, n))) / A[i, i]
        if np.linalg.norm(x - x0) < tol:
            print(f'Количество итераций: {k}')
            return x
        x0 = x.copy()
    print(f'Количество итераций: {k}')
    raise x

In [33]:
A = np.array([[20.9, 1.2, 2.1, .9],[1.2, 21.2, 1.5, 2.5],[2.1, 1.5, 19.8, 1.3], [.9, 2.5, 1.3, 32.1]])
B = np.array([[21.7],[27.46],[28.76], [49.72]])
x0 = np.zeros(len(B))

In [37]:
%%timeit 
method_seidel(A,B,x0)

698 µs ± 26.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [38]:
%%timeit 
method_iteration(A, B)

1.88 ms ± 36.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [50]:
method_seidel(A,B,x0)

Количество итераций: 8


array([0.8, 1. , 1.2, 1.4])

In [51]:
method_iteration(A, B)

15


array([[0.8],
       [1. ],
       [1.2],
       [1.4]])

# Вывод
### Метод Зейделя быстрее метода простой итерации примерно в 2.5 раза и количество итераций в 2 раза меньше

# Метод Гаусса

In [84]:
def gaussian_elimination(A, b):
    n = len(b)
    Ab = np.hstack((A, b.reshape(n, 1)))  # объединяем матрицу A и вектор b в расширенную матрицу Ab

    for i in range(n):
        # ищем максимальный элемент в i-м столбце и переставляем строки, чтобы он был на главной диагонали
        max_row = i + np.argmax(np.abs(Ab[i:, i]))
        Ab[[i, max_row]] = Ab[[max_row, i]]
        
        # приводим i-ю строку к единичному виду, деля на элемент Ab[i, i]
        Ab[i] /= Ab[i, i]

        # вычитаем i-ю строку из всех нижних строк, чтобы обнулить i-й столбец
        Ab[i+1:] -= Ab[i] * Ab[i+1:, i:i+1]
    
    print(Ab)
    # обратный ход метода Гаусса для нахождения решения
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = Ab[i, -1] - Ab[i, :-1] @ x
    return x

In [85]:
%%time
gaussian_elimination(A, B)

[[1.         0.05741627 0.10047847 0.0430622  1.03827751]
 [0.         1.         0.06527941 0.1158636  1.24054433]
 [0.         0.         1.         0.05383594 1.27537032]
 [0.         0.         0.         1.         1.4       ]]
Wall time: 5.74 ms


array([0.8, 1. , 1.2, 1.4])